version: '3.9'

services:
    php:
        build: docker/php
        volumes:
            -   .:/app
        working_dir: /app
        depends_on:
            composer:
                condition: service_completed_successfully

    composer:
        build: docker/php
        volumes:
            - .:/app
        working_dir: /app
        command: composer install