version: '3.9'

services:
    php:
        build: docker/php
        volumes:
            -   .:/app
        working_dir: /app
        env_file:
            -   .env
        depends_on:
            db:
                condition: service_healthy
            migration:
                condition: service_completed_successfully
            composer:
                condition: service_completed_successfully

    db:
        build: docker/mysql
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
            interval: 10s
            timeout: 2s
            retries: 10
        env_file:
            - .env
        ports:
            - "3303:3306"

    migration:
        build: docker/migration
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - ./sql:/sql:cached
        env_file:
            - .env

    composer:
        build: docker/php
        volumes:
            - .:/app
        working_dir: /app
        command: composer install
